import React, { Component } from 'react';
import { Button } from 'react-bootstrap';
//Render
export default class AvisoPriv extends Component {
    render(){
        return(
            <div>
                <div className="gridcontainer centro">
                    <div className="itemav">
                        <p><strong>Aviso de Privacidad</strong></p>
                        <section id="sec1" style={{textAlign:'justify'}}>
                            <p>En cumplimiento de lo dispuesto por la Ley Federal de Protecci&oacute;n de Datos Personales en Posesión de los Particulares (en lo sucesivo la “Ley”), el Reglamento de la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares (en delante el “Reglamento”) y los Lineamientos del Aviso de Privacidad publicado en el Diario Oficial de la Federación el d&iacute;a 17 de enero de 2013 (en lo sucesivo los “Lineamientos”) y dem&aacute;s disposiciones aplicables, el Centro de Desarrollo Humano y Tecnol&oacute;gico A.C. (en lo sucesivo “CDHT”), desea hacer del conocimiento del Usuario de los dominios, aplicaciones m&oacute;viles o sitios web <a href="https://www.turismointeligentehgo.com">www.turismointeligentehgo.com</a> y todo lo que de ellos derive, (en lo sucesivo el “Usuario”), su Aviso de Privacidad respecto del tratamiento y protección de los datos de car&aacute;cter personal de aquellas personas que voluntariamente se comunican y/o contactan, de forma enunciativa m&aacute;s no limitativa, a trav&eacute;s de correo electr&oacute;nico, telef&oacute;nicamente o cualquier otro medio electr&oacute;nico, verbal o escrito con CDHT, llenen formularios en que se recaben datos personales y/o que ingresen al sitio web o aplicación m&oacute;vil aqu&iacute; mencionados, si es que esto implica la comunicaci&oacute;n de sus datos personales.</p>
                            <p>Para todos los efectos relacionados con el presente Aviso de Privacidad, el responsable de los datos personales es CDHT, con domicilio el ubicado en San Juan 971, Fraccionamiento Carbonera, Mineral de la Reforma, Estado de Hidalgo, México C.P. 42184; expidiendo y poniendo a disposici&oacute;n del Usuario el presente Aviso de Privacidad, bajo los siguientes t&eacute;rminos:</p>
                        </section>
                        <section id="sec2" style={{textAlign:'justify'}}>
                            <p><strong>I. Finalidad del tratamiento de sus datos personales.</strong> La informaci&oacute;n personal que proporcione el Usuario ser&aacute; &uacute;nicamente utilizada para brindarle servicios y asesor&iacute;a relacionados con la salud personal del Usuario, mismos que son generados mediante mecanismos de inteligencia artificial a trav&eacute;s de la Aplicaci&oacute;n, Sitio Web o bien, de forma presencial.</p>
                            <p>Asimismo, sus datos personales podr&aacute;n ser utilizados para las siguientes actividades secundarias: i) cómo medio por el cual se establecer&aacute; comunicaci&oacute;n con el Usuario en caso de requerirse; ii) servicios relacionados con la cobranza (en los casos que aplique por servicios adicionales contratados); ii) generaci&oacute;n de reportes o sugerencias a trav&eacute;s del funcionamiento de algoritmos y el procesamiento de inteligencia artificial ; iv) servicios relacionados con la cobranza y administración, tales como: facturación y cancelaciones (en los casos que aplique por publicidad o patrocinios); v) conocer la experiencia del Usuario respecto a la aplicaci&oacute;n y recomendaciones a través de encuestas, evaluaciones o similares; y/o, vi) enlazar la informaci&oacute;n del Usuario con usuarios de sus servicios, quienes podr&aacute;n contactar a los negocios de acuerdo con la informaci&oacute;n contenida en la aplicaci&oacute;n Destinos Tur&iacute;sticos Inteligentes (DTI). Lo anterior con el prop&oacute;sito de ofrecer diversos servicios que prestan terceros</p>
                            <p>Aunado a ello existen actividades terciarias para las cuales ser&aacute;n utilizados los datos personales no sensibles como son: i) fines mercadot&eacute;cnicos; ii) fines publicitarios; iii) prospecci&oacute;n comercial; iv) hacer llegar al cliente promociones, descuentos u ofertas exclusivas con otros proveedores tur&iacute;sticos.</p>
                            <p>En caso de no estar conforme con las finalidades de las actividades descritas en el primer párrafo del primer numeral de este documento el Usuario deber&aacute; abstenerse de utilizar la aplicaci&oacute;n m&oacute;vil y/o sitio web.</p>
                            <p>Si usted no est&aacute; de acuerdo con las finalidades secundarias o terciarias, podr&aacute; manifestar su negativa siguiendo el mecanismo previsto en el numeral “VII” del presente Aviso. Es preciso se&ntilde;alar que, en caso de actualizarse el supuesto antes se&ntilde;alado, CDHT no le podr&aacute; brindar los servicios que presta de forma correcta y &eacute;ste no ser&aacute; responsable por tal situaci&oacute;n.</p>
                        </section>
                        <section id="sec3" style={{textAlign:'justify'}}>
                            <p><strong>II. Datos personales solicitados.</strong> Para efectos del presente Aviso de Privacidad se entender&aacute; por dato de car&aacute;cter personal, cualquier informaci&acute;n que se recabe concerniente a personas f&iacute;sicas o morales identificadas o identificables; y por Usuario, a cualquier persona f&iacute;sica o moral identificada o identificable que comunique sus datos de car&aacute;cter personal a trav&eacute;s del sitio web o aplicaci&oacute;n aqu&iacute; mencionados que de manera enunciativa m&aacute;s no limitativa pudiera ser a trav&eacute;s de i) correo electr&oacute;nico; ii) llenado de formularios por los que se recaban datos personales; iii) participaci&oacute;n en campa&ntilde;as; iv) creaci&oacute;n de perfiles o cuentas de Usuario; v) uso de blogs, chats, foros; vi) publicaci&oacute;n de contenidos; y vii) en general el uso de cualquier servicio del sitio web o aplicaci&oacute;n m&oacute;vil que impliquen la comunicaci&oacute;n de sus datos personales.</p>
                            <p>Los datos personales que CDHT recabar&aacute; del Usuario, de manera enunciativa y no limitativa son: i) Nombre completo; ii) domicilio; iii) edad; iv) correo electr&oacute;nico; v) CURP; iv) copia de credencial del Instituto Nacional Electoral o cualquier otra identificaci&oacute;n oficial; v) Nombre del negocio; vi) n&uacute;mero de tel&eacute;fono fijo, oficina o celular; vii) ubicaci&oacute;n geogr&aacute;fica; viii) Datos espec&iacute;ficos del negocio; y/o ix) fotograf&iacute;a del negocio, el cual podr&iacute;a contener informaci&oacute;n sensible como: precios, n&uacute;mero de habitaciones, men&uacute;, y todos aquellos datos que sean fundamentales para que el turista conozca el negocio.</p>
                            <p>Para la realizaci&oacute;n de las actividades secundarias enumeradas en el segundo p&aacute;rrafo del numeral I de este Aviso de Privacidad, los datos personales podr&aacute;n ser recabados indirectamente a trav&eacute;s de Cookies, Web Beacons, y/o Pixel Tags, con la finalidad de obtener datos de direcciones IP, tipo de navegadores, sistemas operativos, p&aacute;ginas web visitadas, duraci&oacute;n de tiempo de navegaci&oacute;n, monitorear comportamiento de los usuarios y sus preferencias de compra. En caso de que el usuario as&iacute; lo quiera, podr&aacute; remover o deshabilitar estas herramientas, pudiendo a su vez solicitar asesor&iacute;a de CDHT para dicha tarea.</p>
                        </section>
                        <section id="sec4" style={{textAlign:'justify'}}>
                            <p><strong>III. Sobre Redes Sociales.</strong> CDHT hace del conocimiento del Usuario que est&aacute; presente en redes sociales, como Instagram, YouTube, Facebook y Twitter. El tratamiento de los datos de los Usuarios que se hagan seguidores de las p&aacute;ginas oficiales de DTI se regir&aacute; por las condiciones previstas en los t&eacute;rminos y condiciones de la red social que corresponda en virtud de que cualquier dato que la red social requiera sea recabado es responsabilidad de &eacute;sta y no de CDHT por lo que se recomienda el acceso a la pol&iacute;tica de privacidad y condiciones de uso de las mencionadas p&aacute;ginas o en su caso, de la propia red social, con el fin de conocer la informaci&oacute;n derivada del tratamiento de los datos de car&aacute;cter personal y especialmente las condiciones y finalidades a las que ser&aacute;n destinados los datos que forman parte del perfil del Usuario.</p>
                        </section>
                        <section id="sec5" style={{textAlign:'justify'}}>
                            <p><strong>IV. Resguardo de datos personales.</strong> Los datos personales del Usuario ser&aacute;n resguardados con base en los principios de licitud, consentimiento, informaci&oacute;n, calidad, finalidad, lealtad, proporcionalidad y responsabilidad, mismos que se encuentran consagrados en la Ley. La creaci&oacute;n de bases de datos con informaci&oacute;n sensible ser&aacute; &uacute;nicamente para la prestaci&oacute;n de los servicios principales y secundarios, indicados en el apartado I de este aviso de privacidad, mismos que ser&aacute;n resguardados diligentemente con m&eacute;todos inform&aacute;ticos, administrativos y digitales.</p>
                        </section>
                        <section id="sec6" style={{textAlign:'justify'}}>
                            <p><strong>V. Transferencia de informaci&oacute;n personal e informaci&oacute;n sensible.</strong> CDHT no transmitir&aacute; la informaci&oacute;n personal y sensible recabada. No obstante, el Usuario podr&aacute; solicitar que se transfiera la informaci&oacute;n personal y sensible &uacute;nicamente a los profesionales especializados que se encuentren plenamente identificados con nombre completo, especialidad profesional y n&uacute;mero de c&eacute;dula profesional al solicitarle a trav&acute;s de la aplicaci&oacute;n, una consulta.</p>
                            <p>Para ello el Usuario reconoce que manifestar&aacute; su consentimiento expreso, a trav&eacute;s del uso de una cuenta del Usuario que es para uso exclusivo de la aplicaci&oacute;n, misma que tendr&aacute; el car&aacute;cter de personal y que para todos los efectos del art&iacute;culo 9 de la Ley, ser&aacute; considerado como un mecanismo de autentificaci&oacute;n.  El Usuario reconoce que es el &uacute;nico responsable de toda la actividad que ocurra en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contrase&ntilde;a de su Cuenta de Usuario.</p>
                            <p>Asimismo, CDHT para los efectos de las actividades terciarias indicadas en el apartado I de este Aviso de Privacidad, podr&aacute; transferir la informaci&oacute;n del Usuario con las empresas filiales a la empresa, como son instancias estatales, entre otros, con los que expresamente mantengan convenios de alianzas; esto con el fin de proporcionar al Usuario un beneficio econ&oacute;mico o de promociones u ofertas.</p>
                            <p>De igual manera, CDHT podr&aacute; transferir la informaci&oacute;n personal recabada cuando esta sea solicitada por autoridades o dependencias, como son de manera enunciativa m&aacute;s no limitativa, las siguientes: Procuradur&iacute;a Federal del Consumidor, la Secretar&iacute;a de Hacienda y Cr&eacute;dito P&uacute;blico; &uacute;nicamente, cuando dicha situaci&oacute;n sea imperativa por una solicitud oficial o documento judicial expreso.</p>
                        </section>
                        <section id="sec7" style={{textAlign:'justify'}}>
                            <p><strong>VI. Cambios o modificaciones al Aviso.</strong> CDHT se reserva el derecho de modificar el presente Aviso por lo que hace de su conocimiento que cualquier cambio o modificaci&oacute;n al contenido del presente ser&aacute; publicado, de manera generalizada dentro de su aplicaci&oacute;n (DTI) y p&aacute;gina web (www.turismointeligentehgo.com).</p>
                        </section>
                        <section id="sec8" style={{textAlign:'justify'}}>
                            <p><strong>VII. Medios para ejercer sus derechos.</strong> De conformidad con lo dispuesto en la Ley, el Usuario podr&aacute; acceder, rectificar y cancelar sus datos personales, as&iacute; como oponerse a la divulgaci&oacute;n de los mismos a trav&eacute;s de los procedimientos que CDHT ha implementado a trav&eacute;s de su &Aacute;rea Administrativa. El Usuario podr&aacute; Acceder, Rectificar, Cancelar y Oponerse (Derechos ARCO), a la divulgaci&oacute;n de sus datos, revocar su consentimiento o manifestar negativa al tratamiento de los mismos, enviando un correo electr&oacute;nico a <a href="mailto:contacto@cdht.mx">contacto@cdht.mx</a> dirigido a CDHT, indicando lo siguiente:</p>
                            <p>
                                <ul>
                                    <li>1. Nombre completo del titular de los datos personales.</li>
                                    <li>2. Domicilio o correo electr&oacute;nico al que podr&aacute;n dirigirse todas las comunicaciones relacionadas con la solicitud.</li>
                                    <li>3. Copia digitalizada de un documento oficial donde se acredite la identidad del solicitante, pudiendo ser enunciativa más no limitativa: credencial para votar, licencia de conducir, pasaporte, y/o cualquier otro documento que facilite la localizaci&oacute;n de datos personales</li>
                                    <li>4. Descripci&oacute;n clara y precisa de los datos personales respecto de los que se busca ejercer alguno de sus derechos o la actividad sobre la cual se desea limitar el uso de los datos personales.</li>
                                </ul>
                            </p>
                            <p>CDHT tendr&aacute; un per&iacute;odo no mayor a 20 (veinte) d&iacute;as h&aacute;biles para responder la solicitud por el medio indicado por el Usuario. No obstante, si el usuario considera que han sido vulnerados sus derechos respecto de la protecci&oacute;n de datos personales, tiene el derecho de acudir a la autoridad correspondiente para defender su ejercicio. La autoridad es el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI).<br/><br/>De conformidad con el art&iacute;culo octavo de la Ley, por el simple hecho de no manifestar oposici&oacute;n al leer el presente Aviso se entender&aacute; la aceptaci&oacute;n total a los t&eacute;rminos de este.</p>
                        </section>
                    </div>
                </div>
                <div className="centro">
                    <Button variant="outline-secondary" className="buttonFormGrid sombra btnText" size="sm" onClick={this.props.handleClose}>Cerrar</Button>
                </div>
            </div>
        )
    }
} 
